### ISSUE TITLE
Integration with spock 2.0

### ISSUE THREAD

**Issue by mihalichzh** [reportportal/agent-java-spock#32]
Hi guys!
Are there any plans on adding support for spock 2.0?

**Comment by HardNorth** [comment]
No. According to my observations there were no usage of current spock agent by users this year. Well, either none want to share statistics with us, either it is so unpopular. Anyway there is no motivation to invest any efforts into this agent.

**Comment by HardNorth** [comment]
Here we go: https://github.com/reportportal/agent-java-spock/releases/tag/5.1.0-RC-6

**Comment by mihalichzh** [comment]
Nice, I'm looking forward for your final decision based on these statistics then :)

**Comment by mihalichzh** [comment]
Hi @HardNorth ! I spent some time investigating compatibility issues of the agent-java-spock with Spock 2.0 and seems that it can be fixed literally with a couple of code lines in ReportPortalSpockListener class. The root cause is that Spock 2.0 depends on JUnit 5 instead of JUnit 4 and thus way of retrieving some meta-info of test entities had changed (check [code comparison](https://github.com/reportportal/agent-java-spock/compare/develop...mihalichzh:develop) for more details).

Probably, I can contribute this kind of fix, but not sure how to do it. Am I right that it is better to create a separate repo for spock 2.0 agent (similar to how agents for different versions of cucumber are published here)?

**Comment by HardNorth** [comment]
@mihalichzh Thanks for the investigation! No, we decided this was a bad practice, since it's increasing the amount of code we need to support. Please try to make it backward compatible.

**Comment by mihalichzh** [comment]
@HardNorth Thanks for your feedback :) Probably, it will require some tricky things related to classloading, since there are a wast of packages/classnames which are equal between spock and spock 2.0. Did you guys managed to implement something similar in the past so I can check it out as an example?

**Comment by HardNorth** [comment]
Not from our code, but you may use something like that:
https://github.com/junit-team/junit4/blob/610155b8c22138329f0723eec22521627dbc52ae/src/main/java/org/junit/rules/TemporaryFolder.java#L235

**Comment by mihalichzh** [comment]
@HardNorth Hi! I've opened PR #34 fixing incompatibility issues.

**Comment by HardNorth** [comment]
@mihalichzh Released: https://github.com/reportportal/agent-java-spock/releases/tag/5.1.0
