### ISSUE TITLE
Extension should register IGlobalExtension itself.

### ISSUE THREAD

**Issue by leonard84** [reportportal/agent-java-spock#42]
**Describe the bug**
The project [instructs](https://github.com/reportportal/agent-java-spock#step-72---make-reportportal-agent-invoked-by-the-tests) the users to create the service entry manually, instead of just providing it itself.

**Steps to Reproduce**
1. add reportportal agent-java-spock to a project

**Expected behavior**
Extension works out of the box

**Actual behavior**
User has to manually create the ServiceLoader entry for the extension.

**Dependency versions**
agent-java-spock 5.1.3

**Additional context**
`IGlobalExtension` is using the java `ServiceLoader` interface and libraries that provide service should advertise it themselves and not require users to do that.

**Comment by HardNorth** [comment]
@leonard84 This makes troubles for those users who want customize the agent, so I'm not going to change it, sorry.

**Comment by HardNorth** [comment]
@leonard84 if I include `IGlobalExtension` file into jar-file it won't be possible to just extend `ReportPortalSpockExtension` and `ReportPortalSpockListener` and put it in the test project. One will hate to create it's own library, configure re-packing logic to not pick `IGlobalExtension` and only then use their custom extension classes.

**Comment by leonard84** [comment]
Is customizing the extension such a common use-case? It isn't documented in the readme at least.

If it is only about customizing `ReportPortalSpockListener` wouldn't it make more sense to use a `ServiceLoader` for that class and use a fallback to the default listener, if no custom listener is registered?
This would allow a seamless default usage and still offer customization options if needed.
